version: '3.9'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./cmd/app/config:/app/config
    ports:
      - "8090:8090"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: Forgetto2011
      DB_NAME: marketplace

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: Forgetto2011
      POSTGRES_USER: postgres
      POSTGRES_DB: marketplace
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
