CREATE TABLE users (
    ID    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Email  varchar(50) NOT NULL,
    Password varchar(200) NOT NULL
);    
CREATE TABLE cards (
    ID    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Header  varchar(50) NOT NULL,
    Data varchar(200) NOT NULL,
    ImageAddress varchar(200) NOT NUll,
    Price int NOT NULL,
    User_id INT references users(ID) NOT NULL,
    Email varchar(50) Not null,
    Created_at timestamp default current_timestamp
);

